language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/attomos/ogmf.vim.git
script: |
  vim -Nu <(cat << VIMRC
  set rtp+=vader.vim
  set rtp+=.
  VIMRC) -c 'Vader! test/*' > /dev/null
